### PR TITLE
Did some typescript

### PR DESCRIPTION
**Pull request by NateCreedDonato**
Did some typescript changes, not completely done as yet

### CODE REVIEW

**Comment by IsmailM** [comment]
Hey @NateCreedDonato - does this still need to be merged? 

Not sure what this is?

**Comment by NateCreedDonato** [comment]
Hi @IsmailM , the changes on this pull request should be on the latest pull request, so you won't need to merge it anymore.

**Comment by IsmailM** [comment]
Thanks @NateCreedDonato.

In the future, please close old PRs that are no longer relevant :)

**Comment by NateCreedDonato** [comment]
Thank you @IsmailM.

I will take note of that for future PRs

**Pull request closed without merging**
